### ISSUE TITLE
Testar códigos da primeira entrega

### ISSUE THREAD

**Issue by fronchetti** [LLVN/Felipe#11]

**Comment by viniciusRib** [comment]
Erros encontrados durante o teste:

- Campo "pesquisar" não funciona

- O campo de documentos adicionados não está quebrando linhas

- Na sessão "adicionar documentos", o botão "adicionar" não aparece de início. Colocar ele visível sem a barra de rolagem..

**Comment by viniciusRib** [comment]
Erros encontrados durante o teste:
- Não está inserindo as dependências no banco de dados
- A alteração de dados não está sendo salva no banco de dados.
